services:
  nginx:
    image: "nginx:1.25.2-alpine"
    container_name: "nginx"
    restart: "always"
    ports:
      - 80:80
      - 443:443
      - 27017:27017 # Para poder acceder a mongodb mientras se desarrolla
    volumes:
      - ${HOME}/nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ${HOME}/ssl:/ssl/
    networks:
      - network
  martin:
    container_name: "martin"
    command:
    - "/tiles"
    image: "ghcr.io/maplibre/martin:main"
    restart: "always"
    ports:
    - "3000"
    volumes:
    - "./tiles:/tiles"
    depends_on:
      - nginx
    networks:
      - network
  mongodb:
    container_name: "mongodb"
    image: "mongodb/mongodb-community-server:latest"
    ports:
      - "27017"
    restart: "always"
    env_file: mongodb/mongodb.env
    volumes:
      - mongodatabase:/data/db
      - ${HOME}/mongodb/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    depends_on:
      - nginx
    networks:
      - network
  api:
    container_name: "api"
    build: "./api"
    restart: "always"
    env_file: mongodb/mongodb.env
    ports:
      - "8081"
    depends_on:
      - nginx
      - mongodb
    networks:
      - network
  web-app:
    container_name: "webapp"
    build: "./web"
    ports:
      - "8080"
    volumes:
      - ${HOME}/web/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nginx
      - api
      - mongodb
      - martin
    networks:
      - network
volumes:
  mongodatabase:
networks:
  network:
    driver: bridge
version: '3.7'