services:
  martin:
    container_name: "martin"
    command:
    - "/tiles"
    image: "ghcr.io/maplibre/martin:main"
    restart: "always"
    ports:
    - "3000:3000"
    volumes:
    - "./tiles:/tiles"
  mongodb:
    container_name: "mongodb"
    image: "mongodb/mongodb-community-server:latest"
    ports:
      - "27017:27017"
    restart: "always"
    env_file: mongodb/mongodb.env
    volumes:
      - mongodatabase:/data/db
      - ${HOME}/mongodb/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
volumes:
  mongodatabase:
version: '3'